### PR TITLE
Feature/wif lume ci

### PR DESCRIPTION
**Pull request by sgarcia1996**

### CODE REVIEW

**Comment by sgarcia1996** [comment]
In the previous version it does a comparison with GKE as an environment variable. I have adapted it, but can you explain that comparison? I do not get it (Line 76 new version)

**Review by franciscorode — APPROVED** [review]

**Comment by franciscorode** [comment]
> In the previous version it does a comparison with GKE as an environment variable. I have adapted it, but can you explain that comparison? I do not get it (Line 76 new version)

Only make the authentication to google if these env variables are passed, I guess it is because some servicess (not all) need download content from GCS for testing and need to auth for do it and others not

**Comment by sgarcia1996** [comment]
> but why is it defined in an environment variable again, instead of using the one defined in requeriment?

**Comment by franciscorode** [comment]
> > but why is it defined in an environment variable again, instead of using the one defined in requeriment?

I don't know that, I think it's not necessary

**Pull request merged**
