### PR TITLE
feat: update setup-python and setup-node in lume-ci action

### PR DESCRIPTION
**Pull request by acostapazo**

### CODE REVIEW

**Review by fgsalomon — COMMENTED** [review]
Is there a way to control when to use the cache? I think @franciscorode had problems with the cache in the past and used `inputs.use_cache` flag for this.

**Comment by franciscorode** [comment]
> Is there a way to control when to use the cache? I think @franciscorode had problems with the cache in the past and used `inputs.use_cache` flag for this.

Yes, [here](https://github.com/alice-biometrics/actions/pull/20) I had the problem. There doesn't seem to be an option to disable it in the [doc](https://github.com/actions/setup-python#caching-packages-dependencies) :pensive:

**Comment by acostapazo** [comment]
I had not noticed it. I guess the new version solves the caching issues, but it's interesting our control on this feature.

"The cache input is optional, and caching is turned off by default." 
https://github.com/actions/setup-python#caching-packages-dependencies

Supported values are pip, pipenv, poetry (https://github.com/actions/setup-python/blob/21c0493ecfd34b1217f0a90ec19a327f3cc0a048/action.yml#L9)

I don't know what happens if we add an empty value to cache parameter... We should review [this](https://github.com/actions/setup-python/blob/main/dist/setup/index.js)

**Comment by acostapazo** [comment]
I've tested and the update worth it (or not xD) :

Before:
Screenshot 2022-04-11 at 17 27 06

After:
Screenshot 2022-04-11 at 17 27 33

Maybe, we can keep our `use_cache` feature with something similar to:

```yaml
      - name: Setup Python (without cache)
        if: ${{ inputs.language == 'python' && inputs.use_cache == false}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python_version }}
      - name: Setup Python (with cache)
        if: ${{ inputs.language == 'python' && inputs.use_cache == true }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python_version }}
          cache: pip
          cache-dependency-path: '**/*requirements.txt'
```

**Pull request merged**
